### ISSUE TITLE
NoMethodError on Resume Order

### ISSUE THREAD

**Issue by mamhoff** [magiclabs/spree_payone#7]
When you have a completed order, then mark it as "paid", then cancel it (second button on the top in `Admin::Orders#edit`) you get the following error messages: 
```
NoMethodError (undefined method `success?' for nil:NilClass):
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree_payone-09eca3459122/app/models/spree/payment_decorator.rb:39:in `handle_response'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/core/app/models/spree/payment/processing.rb:73:in `cancel!'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/core/app/models/spree/order.rb:646:in `block in after_cancel'
  activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `each'
  activerecord (4.2.3) lib/active_record/relation/delegation.rb:46:in `each'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/core/app/models/spree/order.rb:646:in `after_cancel'
  state_machines (0.2.2) lib/state_machines/eval_helpers.rb:58:in `evaluate_method'
  state_machines (0.2.2) lib/state_machines/callback.rb:192:in `block in run_methods'
  state_machines (0.2.2) lib/state_machines/callback.rb:191:in `each'
  state_machines (0.2.2) lib/state_machines/callback.rb:191:in `run_methods'
  state_machines (0.2.2) lib/state_machines/callback.rb:159:in `call'
  state_machines (0.2.2) lib/state_machines/transition.rb:394:in `block (2 levels) in after'
  state_machines (0.2.2) lib/state_machines/transition.rb:394:in `each'
  state_machines (0.2.2) lib/state_machines/transition.rb:394:in `block in after'
  state_machines (0.2.2) lib/state_machines/transition.rb:392:in `catch'
  state_machines (0.2.2) lib/state_machines/transition.rb:392:in `after'
  state_machines (0.2.2) lib/state_machines/transition.rb:195:in `run_callbacks'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:127:in `run_callbacks'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:63:in `block (2 levels) in perform'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:63:in `catch'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:63:in `block in perform'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:182:in `block in within_transaction'
  state_machines (0.2.2) lib/state_machines/transition.rb:171:in `block in within_transaction'
  state_machines (0.2.2) lib/state_machines/machine.rb:1866:in `within_transaction'
  state_machines (0.2.2) lib/state_machines/transition.rb:170:in `within_transaction'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:181:in `within_transaction'
  state_machines (0.2.2) lib/state_machines/transition_collection.rb:62:in `perform'
  state_machines (0.2.2) lib/state_machines/transition.rb:163:in `perform'
  state_machines (0.2.2) lib/state_machines/event.rb:155:in `fire'
  state_machines (0.2.2) lib/state_machines/event.rb:219:in `block in add_actions'
  state_machines (0.2.2) lib/state_machines/machine.rb:725:in `call'
  state_machines (0.2.2) lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
  state_machines (0.2.2) lib/state_machines/event.rb:224:in `block in add_actions'
  state_machines (0.2.2) lib/state_machines/machine.rb:725:in `call'
  state_machines (0.2.2) lib/state_machines/machine.rb:725:in `block (2 levels) in define_helper'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/core/app/models/spree/order.rb:543:in `block in canceled_by'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
  activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
  activerecord (4.2.3) lib/active_record/transactions.rb:277:in `transaction'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/core/app/models/spree/order.rb:542:in `canceled_by'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/spree-acd2b81dc584/backend/app/controllers/spree/admin/orders_controller.rb:88:in `cancel'
  actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `call'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
  dragonfly (1.0.10) lib/dragonfly/middleware.rb:14:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  /Users/anselm/.rvm/gems/ruby-2.2.1@brandeins/bundler/gems/alchemy_cms-110e25f2b9e0/lib/alchemy/middleware/rescue_old_cookies.rb:10:in `call'
  activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.1.0) lib/airbrake/rails/middleware.rb:13:in `call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:18:in `middleware_call'
  web-console (2.0.0) lib/action_dispatch/debug_exceptions.rb:13:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  dragonfly (1.0.10) lib/dragonfly/cookie_monster.rb:9:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.1.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `catch'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.5) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.5) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.3) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `tap'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.3) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:8:in `require'
  bin/rails:8:in `<top (required)>'
  spring (1.3.6) lib/spring/client/rails.rb:28:in `load'
  spring (1.3.6) lib/spring/client/rails.rb:28:in `call'
  spring (1.3.6) lib/spring/client/command.rb:7:in `call'
  spring (1.3.6) lib/spring/client.rb:26:in `run'
  spring (1.3.6) bin/spring:48:in `<top (required)>'
  spring (1.3.6) lib/spring/binstub.rb:11:in `load'
  spring (1.3.6) lib/spring/binstub.rb:11:in `<top (required)>'
  bin/spring:13:in `require'
  bin/spring:13:in `<top (required)>'
  bin/rails:3:in `load'
  bin/rails:3:in `<main>'
```

**Comment by mamhoff** [comment]
This is taking time. Apparently, you can't use PaymentMethods that are not from Spree::Payone with this gem (`Cheque` is from Spree::Core)
